<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../2 - Application/PickupReservations.Application/PickupReservations.Application.csproj" />
    <ProjectReference Include="../../3 - Domain/PickupReservations.Domain/PickupReservations.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>
</Project>
